### ISSUE TITLE
Cannot find module '/usr/local/lib/node_modules/fs/promises' 

### ISSUE THREAD

**Issue by nikolaos83** [betschki/ghost-myrtle#1]
I have been trying to run the app but my efforts have been fruitless and IDK how to proceed because I'm not very familiar with nodejs. I tried installing fs but it doesn't resolve the issue:

---------------------------------------------------------------------------------- 

root@9c97f7225753:/# myrtle config
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/local/lib/node_modules/fs/promises' imported from /usr/local/lib/node_modules/ghost-myrtle/config.js
    at finalizeResolution (internal/modules/esm/resolve.js:285:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
root@9c97f7225753:/#

**Comment by nikolaos83** [comment]
Hmm, I think I need a newer version of Nodejs, right? I supposed apt-get would install the latest version for Ubuntu 22 but that doesn't seem to be the case.
--------------------------------------------------------------------------
root@9c97f7225753:/usr/local/lib/node_modules/ghost-myrtle# node -v
v12.22.9

**Comment by betschki** [comment]
I have tested this with Node 18 and Node 20.

`fs.Promises` should be available from Node 12 upwards, but since Node 12 is massively out of date either way, I'd suggest updating.

Closing the issue – an upgrade of the Node version should do the trick :)

**Comment by nikolaos83** [comment]
Yes, it solved the issue! I fired up a Ubuntu container and used the commands below to get it working. Thanks!

-----------------------------------------------
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
nvm install 18
nvm use 18
