### ISSUE TITLE
Titles start with quotation mark

### ISSUE THREAD

**Issue by nikolaos83** [betschki/ghost-myrtle#3]
Almost all the titles that come out of this script start with a quotation mark. Copilot has this to say about it. IDK, because I'm just learning JS but maybe you should have a look at it.

"The issue seems to be with the regular expression used in the replace() function. The regular expression ^\d+[\.)]\s+\"|\"$ is looking for a digit at the start of the string followed by a period or a parenthesis, then one or more spaces, and then a quotation mark. It also looks for a quotation mark at the end of the string. However, the | operator in the regular expression is causing the issue. It creates two separate conditions: one for the start of the string and one for the end of the string.

Here’s the corrected function:

```
function cleanTitle(title) {
  // Remove numbering (e.g. 1., 2., 1), 2)) and wrapping quotes
  return title.replace(/^\d+[\.)]\s+\"|\"$/g, '').replace(/^\"|\"$/g, '').trim();
}
```

In this corrected function, I’ve added another replace() function with the regular expression ^\"|\"$. This regular expression looks for a quotation mark at the start or end of the string and replaces it with nothing. This should remove the quotation marks at the start and end of your titles. If you have any more questions or need further clarification, feel free to ask! 😊"

**Comment by betschki** [comment]
@nikolaos83 thank you for reporting this and #2 – i have improved the title cleaning and just merged the changes
